---
# apt related OS tasks

- name: install additional packages
  apt:
    name:
      - zip
      - unzip
      - bzip2
      - gnupg2
      - ffmpeg
      - imagemagick
      - ghostscript
      - libfile-fcntllock-perl
    state: latest
